### PR TITLE
Fix/19 null validator

### LINKED ISSUE #19: [False negative] Getting validate input where `Validator<T>` can be null throws an exception.
Given the follwing code:

```HACK
<?hh // strict

namespace Our\Json;
use namespace Slack\Hack\JsonSchema;

type TNoopSchema = mixed;

final class NoopSchema extends JsonSchema\BaseValidator<TNoopSchema> {

  public static function check(mixed $input, string $_pointer): TNoopSchema {
    return $input;
  }

  <<__Override>>
  final protected function process(): TNoopSchema {
    return self::check($this->input, $this->pointer);
  }
}

```

```HACK
use namespace Our\Json;

<<__EntryPoint>>
async function main_async(): Awaitable<void> {
    require_once __DIR__.'/../../library/autoload.php';
    await library_autoload_async();

    $schema = new Our\NoopSchema(null);
    $schema->validate();
    var_dump($schema->isValid());
    $schema->getValidatedInput();
}
```

`$schema->isValid()` is true, but reading `$schema->getValidatedInput()` results in:
```
Fatal error: Uncaught exception 'Exception' with message 'Can't access validated input since validator is invalid.' in /home/lexidor/STN/website/vendor/slack/hack-json-schema/src/BaseValidator.php:39
```

This is cause by:
```HACK
final public function getValidatedInput(): T {
    if ($this->validated_input === null) {
      if (!$this->validated) { ^^^^^^^^
        throw new \Exception('Must call `validate` before accessing validated input.');
      }
      throw new \Exception("Can't access validated input since validator is invalid.");
    }

    return $this->validated_input;
  }
```

### PR DESCRIPTION
**Pull request by lexidor**
Fixes #19

### CODE REVIEW

**Comment by lexidor** [comment]
@mwildehahn I hate being the guy who pings for a bugfix. However, this one is kinda sad. You can't make a validator which is okay with `null` right now, since BaseValidator makes the implicit assumption that `$this->validated_input === null` means that you have not validated yet. This PR fixes that.

P.S. HHAST will lint generated code (causing _you may not changed a signed source file_ error). That will be a separate PR.

I would also love to hackfmt this whole codebase in one fell swoop, if that is okay with you.

**Comment by lexidor** [comment]
### A note about 629acd5

The default assigned value of `is_invalid` was false, to match the behavior of `isValid()`. This function will return true before `validate()` has been called.
However, I strongly believe that hhvm should shout at you when doing so. I would like to discuss making `isValid()` throw before `validate()` is called, since `true` until proven otherwise is a tad bit unexpected.

File: src/BaseValidator.php [hunk 1]
```diff
@@ -7,23 +7,23 @@
 <<__ConsistentConstruct>>
 abstract class BaseValidator<+T> implements Validator<T> {
   private vec<TFieldError> $errors = vec[];
-  private ?T $validated_input;
-  private bool $validated = false;
+  <<__LateInit>> private T $validated_input;
```
Comment (mwildehahn) [inline src/BaseValidator.php]: TIL about this

File: src/BaseValidator.php [hunk 2]
```diff
@@ -35,15 +35,11 @@ public function __construct(
...
-    if ($this->validated_input === null) {
-      if (!$this->validated) {
-        throw new \Exception(
-          'Must call `validate` before accessing validated input.',
-        );
-      }
-      throw new \Exception(
-        "Can't access validated input since validator is invalid.",
-      );
+    if (!$this->has_been_validated) {
```
Comment (mwildehahn) [inline src/BaseValidator.php]: I think we could just do:

```
if (!$this->validated) {...}
if (!$this->isValid()) {...}
```
and then allow nulls?

It seems odd to me to track `is_valid` since `isValid` is doing the count of errors and `has_been_validated` is essentially the same as `validated`?
